@host = https://localhost:7060

GET {{host}}/api/Category/1
tenant: linkedIn

###

GET {{host}}/api/products/1
tenant: linkedIn

###

POST {{host}}/api/products
tenant: linkedIn
Content-Type: application/json

{
  "name": "Product 4 - linkedIn",
  "description": "My linkedIn product - 1",
  "rate": 5
}